
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EVXhNVEEwTXprME1Wb1hEVE16TURVd09EQTBNemswTVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUpvCkFzLzJMd2hXMlUzSEZaMlhpMUpnVEJOR0VMb3JEbmNTOTZtcmJKQlplSmxQVEZjNUpDZ0p4a1liSW82NitsQnYKVGUzNzl5SEZyeWVKRGVsRVpMbC9XcU1HNy9PdzNzbXA1SEVTZFZ6LzY2a096V25vRGhXaUhGdHgzeEZaQUxoYwplS0REaWE0N3lVMVU3SmEvU3ZzMStQVkQvWEdyeVRwQ0VlVHZjWnJ1dEVKZXdNTHZDNGR5eVZVZ3ZMMWZBc0pECnhQdjJsVTBWSHlmNzRXWVhDeG4yQXVQU3cyOXJ1RmJhSEJHSXBjRzRVTmJuN1ZocHFTc3RwT3pnb0xnTEZ0dEkKeU1zc25BWFRYRU1pcW5yaDFiQ1pkSFVtRVNMUUcwdUtESFUwWXU2NkQra1R1SFFBYnRvRVk4WDVEd2EvK3NaZQplekJ3eFB2bnpnOW1wNldBd3lNQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZIUmNQSk05aVBZUXRGNE8zbDJtMFZ0bkRJWWxNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSWxCSnpjdE12SlIxb3pabXV4NgozZ1hLTWdjS2ZCei9EaHcxb2xoZVlldC92d205ZkxocUFwTXNiVUpqQ1pLSS90aXNJZDV0ZDFQQi9JWTFVbHdzCndESFE0NWhtTlRmVWNPelpudnp6R1F1c2lPaWZldkhhNDNaVWFxN0tXUy9zV29sNC9iWndoOGJYUExKbFhNdGMKVmlCdGw2by96TFVkSjRMVEhDSHI5cjMrb0t6K2VUOTllK3lQMmxXenQ2ZnJ3THQ1YjlHSHBZRjZNNlFkcEhBTApLVTQvZDFWQkZxQ3NNcmxqelgxREo3UUZLdnFXS2Q0eUY0SmxaclVRNGRVWC9ETEhycXBRTXVwUGZZbUVtUElpCnkrYmw4VUpVWXBKOVRWTUYyZ1Z5eDJhc2E4UEo1NUNyYXoyOXMrQm9Hd3JBQjExL2NzR1VEa1kwSlFSNk5FRzYKSHBNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://bcb68913-589f-4eb0-a617-ed748ac19289.us-west-2.linodelke.net:443
  name: lke107740

users:
- name: lke107740-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkRMdHU5WXZ5aXU4SEtCMFlnTVV0ZlRidXQyMkJXNjJtUFdqYUlJc3pVYU0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tbTl2OWgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMzBhYjc2MTQtNGUxZC00NjA1LWFjMjktZjI3NWE1N2NkZTYyIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.DwcCnfnZJcVgLS3rF8uGPTkbb3sMKq7Pl-GxAgggx99fmvT9Gw4wzAVH-QIKj5P4vemoWazgD60Q248JYTIlpvPDocsNK_jCqeOJ8IHVnFqgNHMEuE7dQf1KbA-UB0Q8xagA6LuzQjCw6WzYOFkIchI7PgEjPMQH4577utQQ4hw-LqrsPSSYz21qZDqZX9Bgg5W0Y2oyeHAmHsE6domT2qF-8yH1UPW-SgzkeZPwa73h782ybEvEzhRCvZI-moXApCCc0fy9HO5VheyjbwIEXTphqr887QzUaMJF-XQonuJYMLmxRJeRFPWQ0RSqwaTnzDor0jtOul9gVv567DYuQA

contexts:
- context:
    cluster: lke107740
    namespace: default
    user: lke107740-admin
  name: lke107740-ctx

current-context: lke107740-ctx